---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - iaas.controllers.thalassa.cloud
  resources:
  - blockvolumes
  - loadbalancers
  - natgateways
  - routetableroutes
  - routetables
  - securitygroups
  - snapshotpolicies
  - snapshots
  - subnets
  - targetgroups
  - tfsinstances
  - vpcpeeringconnections
  - vpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iaas.controllers.thalassa.cloud
  resources:
  - blockvolumes/finalizers
  - loadbalancers/finalizers
  - natgateways/finalizers
  - routetableroutes/finalizers
  - routetables/finalizers
  - securitygroups/finalizers
  - snapshotpolicies/finalizers
  - snapshots/finalizers
  - subnets/finalizers
  - targetgroups/finalizers
  - tfsinstances/finalizers
  - vpcpeeringconnections/finalizers
  - vpcs/finalizers
  verbs:
  - update
- apiGroups:
  - iaas.controllers.thalassa.cloud
  resources:
  - blockvolumes/status
  - loadbalancers/status
  - natgateways/status
  - routetableroutes/status
  - routetables/status
  - securitygroups/status
  - snapshotpolicies/status
  - snapshots/status
  - subnets/status
  - targetgroups/status
  - tfsinstances/status
  - vpcpeeringconnections/status
  - vpcs/status
  verbs:
  - get
  - patch
  - update
